### ISSUE TITLE
Consider Brick's "strWrap" alternative to "wordWrap"

### ISSUE THREAD

**Issue by jtdaugherty** [callum-oakley/gotta-go-fast#1]
Hi,

Author of `brick` here. Nice program!

I noticed that you implemented `wordWrap`, but `brick` version `0.20` got `strWrap` and `txtWrap` functions that do what you want. You can see how they work `TextWrapDemo.hs`. I figured I'd let you know in case you'd rather use those.

**Comment by jtdaugherty** [comment]
Actually, I take that back: looking at how you use the results, you need a lower-level thing. That's implemented in my `word-wrap` package.

**Comment by callum-oakley** [comment]
Thanks for taking a look! I'll certainly give `word-wrap` a spin, looks great. I was intending on moving from `String` to `Text` at some point, so will probably try using it then (looks like it only has `Text` functions?)

I'll be sure to let you know if I have any feedback!

P.S. Brick is an absolute pleasure to use – and the docs are brilliant. 10/10

**Comment by jtdaugherty** [comment]
> Thanks for taking a look! I'll certainly give word-wrap a spin, looks great. I was intending on moving from String to Text at some point, so will probably try using it then (looks like it only has Text functions?)

Doing this would save on `pack`/`unpack` calls, too, if you use `Data.Text` routines to read the input file.

> P.S. Brick is an absolute pleasure to use – and the docs are brilliant. 10/10

Awesome - I'm glad you had a good experience with it. :)

**Comment by jtdaugherty** [comment]
I guess this ticket is defunct now that you have merged the `word-wrap` patches.
