### ISSUE TITLE
Single backspace deletes two space characters

### ISSUE THREAD

**Issue by gyvess** [callum-oakley/gotta-go-fast#10]
Gotta Go Fast 0.2.1.1, but this isn't a recently introduced problem.

For a simple example lets say my text file includes the words `dog ate`, I mistyped a space where the character `a` should be, and my cursor now lies at the position of character `t`. Bold characters represent what has already been typed.

<pre>
<b>dog _</b>te
     ^   
</pre>
At this cursor position pressing backspace to correct the error causes my cursor to end up here by removing both previous spaces. I now have to retype space in order to continue.
<pre>
<b>dog</b> ate
   ^   
</pre>
The expected behavior is that the single incorrect space is removed and my cursor is placed at character `a` while also avoiding having to retype the space.

<pre>
<b>dog</b> ate
    ^   
</pre>
I've only been able to induce this behavior with incorrcet spaces preceded by other spaces. If you open a text file and place multiple contiguous spaces then press backspace a single time all previous spaces will be removed until the last previous character or beginning of the entire text example.

**Comment by callum-oakley** [comment]
Good find. I've reproduced this myself, and it doesn't look like the fix will be difficult. Watch this space!

Thanks for the brilliant issue report by the way, very well explained.

**Comment by gyvess** [comment]
Latest commit fixes it, thanks for the quick turnaround.

**Comment by callum-oakley** [comment]
Glad to hear it :)

**Comment by callum-oakley** [comment]
@gyvess just wanted to let you know that I was planning to release the fix to this issue as part of the larger release of v0.3.0.0 which is now out, but you saw my commit on master so got in a bit early! (Really I shouldn't have been developing on master... sometimes I forget other people use my little toy project 😅)

There's a couple of new options so be sure to take a look at the readme if you're curious.
