### ISSUE TITLE
GGF I can't quit you

### ISSUE THREAD

**Issue by ssanj** [callum-oakley/gotta-go-fast#14]
I've tried using `ESC` to exit GGF but it seems to only restart the typing test.

What's the recommended way to exit?

I had to use `CTRL + C` to exit.

If that is the recommended way, it would nice to have it in the README. I'm happy to create a PR if that's the case.

**Comment by callum-oakley** [comment]
`CTRL-C` is indeed the intended way to quit half way through a text, or you can finish the text and hit enter. I added a note to the readme. :)
