### ISSUE TITLE
Text not visible due to color scheme

### ISSUE THREAD

**Issue by ygale** [callum-oakley/gotta-go-fast#6]
Reported by `/u/Aoi32` on reddit:

> ...my default color scheme obscures the text I have not yet typed. Do you think you could set the color of the text you have not yet typed as the inverse of the terminals current color?

You answered:

> Good catch – I'll definitely try and do something along those lines. At the very least I should make the colours configurable...

For me, only the text under the cursor is invisible. But that is an issue.

Using version 0.1.2.0, built from git commit `11e626449ce746f432e52c4b2ac3bcfe0e1b866a`, on Mac OS X 10.10.5, using `stack install`.

**Comment by callum-oakley** [comment]
`v0.1.3.0` includes `--fg-empty` and `--fg-error` options. If you set `fg-empty` to some other colour that doesn't clash with your background then you should be able to see the text.

The colours are

    0: black
    1: red
    2: green
    3: yellow
    4: blue
    5: magenta
    6: cyan
    7: white

If you find one that works well, I would alias `gotta-go-fast` to `gotta-go-fast --fg-empty n`.
